name: Vertical Slice
description: Define a vertical slice with explicit intent and acceptance criteria
body:
  - type: input
    id: task
    attributes:
      label: GSD task file
      description: Link to tasks/... .gsd.md
      placeholder: tasks/2026-02-10-example.gsd.md
    validations:
      required: true
  - type: textarea
    id: intent
    attributes:
      label: Intent
      description: What outcome should users/system observe?
    validations:
      required: true
